eureka:
  instance:
  hostname: discovery
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8060

spring:
  application:
    name: payment-service
  cloud:
    config:
      override-system-properties: false   
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/payment
    username: alibou
    password: alibou
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      acks: -1    
      bootstrap-servers: kafka-service:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.alibou.ecommerce.notification.PaymentNotificationRequest

application:
  config:
    product-url: http://gateway:8222/api/v1/products    


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
