eureka:
  instance:
  hostname: discovery
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
server:
  port: 8090
spring:
  application:
    name: customer-service
  cloud:
    config:
      override-system-properties: false  
  data:
    mongodb:
      username: alibou
      password: alibou
      host: mongodb
      port: 27017
      database: customer
      authentication-database: admin


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  
 